import { Playfair_Display } from "next/font/google";
import "./globals.css";
import NavbarMain from "./components/NavbarMain";
import MobileMenu from "./components/Mobile/MobileMenu";
import FakeMenu from "./components/Mobile/FakeMenu";
import { MenuProvider } from "./context/MenuProvider";
import CustomFooter from "./components/CustomFooter";



const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-playfair-display',
});



export const metadata = {
  title: "Ego Aesthetics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${playfairDisplay.className}`}>{children}
      <div className="hidden md:flex">
      <NavbarMain/>
      </div>
      <div className="md:hidden">
        <MobileMenu/>
      </div>
      {/* <MenuProvider>
        <FakeMenu/>
      </MenuProvider> */}
      
      <CustomFooter/>
      
      </body>
    </html>
  );
}
